{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: {{ include "helm.chart" . }}
    app: {{ include "helm.name" . }}
    app.kubernetes.io/name: {{ include "helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
